### ISSUE TITLE
Add test coverage to hacker_news_pwa

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1023]
At minimum, we should have

* Basic "bootstrap-y" unit test (with DDC).
* Basic "e2e-y" web driver test (with Dart2JS).

**Comment by leonsenft** [comment]
We really should write a simple test with mocked data and page objects to ensure that the feed and items at least render. We [introduced a regression](https://github.com/dart-lang/angular/pull/1495) two months ago that went undetected until today (mostly because it coincided with https://github.com/dart-lang/angular/issues/1305sues/1305).

I'll try to get this done this week.
