### ISSUE TITLE
AST package crashes parsing newlines in attribute values

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1109]
> I see one crash too. This causes a crash, when parsed:
> ```html
>   <child [value]="\'a\n\nb\'"></child>
> ```
> 
> I think it is either the escaped `'` or the new-line characters.
> 
> ... going to see if @MichaelRFairhurst can help here.
> 
> For the other failures, it looks like CSS shimming is not happening anymore.

@MichaelRFairhurst is it possible to get some help here? I imagine this impacts the analyzer plugin too

**Comment by MichaelRFairhurst** [comment]
We don't yet share expression parsing with angular_ast, so this doesn't, but will, affect the plugin too.

I think we ran into this separately though and fixed it...but I can't find the commit.

You said it crashes, is there a stack trace?

**Comment by MichaelRFairhurst** [comment]
I don't think its the newline, I think this is actually invalid.

```
<child [value]="\"a\nb\""></child>
```

would, but as written, that dart code we'll try to parse is `\'a\n\nb\' which is not valid dart.

This brings up an interestingly tricky question, too. Because, say we evaluated the escapes before handing it to dart. Now we get

```
0x??a
b
0x??
```

which is also invalid dart. In fact, even without backslashing the single quotes, it's still an error because it spans multiple lines which dart doesn't allow in string literals.

We should also check that the example I gave that's "valid" works. If we don't remove the escapes, we *still* try to parse invalid dart because `\"a\n\b\"` is not valid dart either.

We should probably be removing escapes for quotes of the correct type within quotes, and leave the rest alone. Or should we also handle `\\` -> `\` ?

**Comment by matanlurey** [comment]
Ah, I see what you mean. Let me bring this internally, run tests.

Maybe this is something we should just fail on (better failure = better, though)

**Comment by MichaelRFairhurst** [comment]
Should this be closed? Do we have tests that confirm we correctly handle `[x]="\"y\""`?

Also I think we don't need to handle `\\`. You need it if you want a `\` in front of a `"` without escaping the `\`, like so: `[x]="foo\\"`. This is not valid dart.

You could in theory want to put a `\\` before an escaped `"`, which would be `\\\"` in dart ie `[x]="\"a quote: \\\" \""` but if we treat `\\"` as a `\` before a `\"`then its still possible albeit unexpected `[x]="\" a quote: \\" \""` which is probably OK since its still well specified.

I do think this means our regex requires some tinkering, though, as we're using the "standard" escapes-in-a-string regex which will treat `"\\"` as a backslash in quotes rather than as a backslash before an escaped quotes character with no matching close quote.

**Comment by MichaelRFairhurst** [comment]
I filed #1122 to track what I've thought about this which is no longer related to the original filing of the ticket
