### ISSUE TITLE
AST expression parser extending Analyzer

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/angular#1112]
Tracking bug for discussions had elsewhere:

angular_ast currently extends the analyzer parser in order to support pipes in expressions. The analyzer and CFE teams have expressed concern with this approach. We need to do something:

1. Copy / fork the entire dart parser into angular_ast, and maintain it indefinitely. 
2. Convince the Analyser and CFE to support our use case
3. "Preprocess" pipes into proper dart syntax before calling the expression parser.
4. Change the pipe syntax to something that is dart-legal syntax.

3 seems like the best long-term solution here.

**Comment by matanlurey** [comment]
Thanks for filing this.

Originally I wanted to do 3, i.e.:

`value | pipe` becomes something like `$pipe(value)`.

This isn't straight forward, though:
* We still have to parse the expression, either with Dart or otherwise, to determine this.
* It's probably non-trivial to just a regular expression to do this.
* It's much harder to understand what `$pipe` is and act on it in the compiler.

/cc @MichaelRFairhurst for other ideas.

**Comment by MichaelRFairhurst** [comment]
3 is definitely non trivial.

Note that it can't be done via regex* because regex can't handle nested
values*. It needs to be handled as a grammar.

It's easy to define the grammar. We can tokenize, and then basically have
this:

```
prog = pipeExpr

pipeExpr = pipeExpr '|' pipeName pipeArgs?
  | matchingTokens

matchingTokens = '(' matchingTokensContents ')

matchingTokensContents = anythingButCloseParenAndPipe
  | matchingContents

pipeArgs = notPipe
  | pipeArgs ':' notPipe

notPipe: matchingTokensContents
  | notPipe matchingTokensContents
```

This lets you parse the paren structure and pipes and handle everything
else with a hands off approach. Should have everything you need to rewrite
the pipes as functions, though there may be some bugs where the dart spec
has lower precedence operators like maybe .. or ?:.

Error ranges get messed up, so we'll have to map dart to original error
ranges and transform every dart error to highlight the correct sections.

More importantly, errors will be bad. Things like "unexpected function
$pipe." Or, "named argument not allowed here" (from : sneaking in).

* Regexes strictly speaking must have finite memory. That means that
parsing matching parens cannot be handled, as you may see an infinite
number of open parens, requiring an infinite number of states to expect the
correct number of close parens, and infinite states means infinite memory.
Many regex engines, however, still support this, because they recognize the
situation and compile to something other than a finite state machine in
this case. So maybe we could do it with regex, I think JS (and therefore
dart) is one of the languages that has this power. But even then, it may
get hairy and ugly especially if there are more operators we want to
handle, or the code handling the matches may not have enough information
for us to preserve offset information in & out. It's just not the right
tool for the job unless we're lucky.

**Comment by matanlurey** [comment]
Marking this blocked until we have a resolution.

**Comment by matanlurey** [comment]
I'm taking this OKR.

**Comment by matanlurey** [comment]
This has been removed from the compiler
