### ISSUE TITLE
Collapse gratuitous CSS whitespace by default

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular#1252]
Just looked at the CSS embedded in a recent compile. Lot's of whitespace that could just be eliminated.

Any reason we don't just do that by default?

```js
C.ap=makeConstList(["footer {\n  background: #212121;\n  position: fixed;\n  z-index: 10;\n  left: 0;\n  bottom: 0;\n  width: 100%;\n  padding: 8px;\n  height: 37px;\n  display: flex;\n}\n\n.loading {\n  height: 100vh;\n  padding: 50px;\n  text-align: center;\n  color: #212121;\n}\n\nfooter div {\n  flex: 1;\n}\n\nfooter a {\n  display: inline;\n}\n\ndiv.next {\n  text-align: right;\n}\n\narticle:last-of-type {\n  margin-bottom: 37px;\n}\n"])
```

**Comment by matanlurey** [comment]
Probably just an oversight honestly.

Though there are some significant whitespace rules in CSS and I'd hate to have to implement a special parser and minifier for this.

**Comment by matanlurey** [comment]
Also it looks like SASS can fulfill this requirement:
https://stackoverflow.com/questions/8980398/sass-watch-with-automatic-minify?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by kevmoo** [comment]
Perhaps we should have an example in our repo (Hacker News?) that uses
sass, then?

**Comment by matanlurey** [comment]
Sounds like a FR for sass_builder not us.

**Comment by leonsenft** [comment]
Unfortunately the CSS is introduced _post_-SASS by package:csslib.

**Comment by matanlurey** [comment]
Owch. Yeah. I don't know if this is doable in a clean way. Let's review at weekly.

**Comment by leonsenft** [comment]
@matanlurey @kevmoo I was looking at the example you provided and realized csslib shouldn't have output any `\n` at all. I recognize those styles from our Hacker News example, which doesn't use style encapsulation.

- For `ViewEncapsulation.None`, we don't process the stylesheets, and output their contents as-is. That's why we're seeing the newlines preserved from the CSS file we wrote by hand.
- For `ViewEncapsulation.Emulated` (default), we do process the stylesheets via csslib, and output their content from csslib ASTs. While this doesn't contain any `\n` and there's less whitespace, it's still not optimally minified.

That leaves us with a few options.

1. We attempt to minify all styles regardless of `ViewEncapsulation`. We could still process CSS for `ViewEncapsulation.None` via csslib in order to use it's (half-hearted) minification, obviously without shimming the styles for encapsulation.

2. We leave minification entirely to the user. A CSS minification builder could be used, similar to sass_builder that runs before the angular builder. It's worth noting that this would _only_ work for `ViewEncapsulation.None`. If `ViewEncapsulation.Emulated` is set, we're going to end up parsing, shimming, and outputting the modified CSS using csslib's minification.

**Comment by kevmoo** [comment]
\#1 sees right to me, with my limited context. Even trivial magnification is good for the user.

**Comment by matanlurey** [comment]
@leonsenft If `1` is trivial, that's my vote, to get at least get us over the bump here.

**Comment by matanlurey** [comment]
(and @leonsenft, if you agree, assign the issue to yourself for the time being)

**Comment by leonsenft** [comment]
1 does seem favorable; however, I'm a little hesitant to enforce use of csslib for all styles, as there are some known issues with it, and perhaps users would have opted for `ViewEncapsulation.None` to avoid them.

I'd be in favor of waiting for our resolution on longterm plans with csslib before using it (or another solution) on CSS that isn't encapsulated. We don't want to use csslib for minification alone if it's suboptimal and causes any friction.

**Comment by matanlurey** [comment]
K. Let's revisit later.

**Comment by TedSander** [comment]
Note you could run Sass on even a CSS file to get compression. I use that somewhere in Google3

**Comment by leonsenft** [comment]
Good point @TedSander!

**Comment by leonsenft** [comment]
Note that as of https://github.com/dart-lang/csslib/pull/69, encapsulated styles are better minified.

**Comment by matanlurey** [comment]
I think we can mark this closed as of https://github.com/dart-lang/csslib/pull/69.

**Comment by leonsenft** [comment]
@matanlurey this issue addressed non-encapsulated styles, which are unaffected by dart-lang/csslib#69.

That said I'm happy to keep this closed and leave minification of non-encapsulated styles to the user for now.
