### ISSUE TITLE
difference with queryParameters in NavigationParams and toUrl()

### ISSUE THREAD

**Issue by lejard-h** [dart-lang/angular#1254]
* 2.0.0-dev.48.0 Dart SDK
* Angular 5.0.0-alpha+10
* Chrome

My route definition
```dart
final searchPath = RoutePath(path: "search");
final _searchRouteDefinition = RouteDefinition.defer(
  routePath: searchPath,
  loader: () async {
    await search_view.loadLibrary();
    return search_view.searchNgFactory;
  },
);
```

I need to pass queryParameters when navigating to this route, at first I was using `toUrl` function

```dart
final params = { "foo": "bar" };
final url = searchPath.toUrl(queryParameters: params); // url == "/search?foo=bar"
router.navigate(url);
```
But the router is not navigating to my view and by using `NavigationParams`

```dart
final url = searchPath.toUrl(); // url == "/search"
router.navigate(url, new NavigationParams(queryParameters: params));
```
It is navigating well to `localhost:8080/#search?foo=bar`.

Is it the normal behaviour of the navigate function ? I am also using `<base href="/">`

**Comment by leonsenft** [comment]
Yes, it's intended that query parameters and fragment identifiers are passed via the optional `NavigationParams` parameter.

Due to popular demand we're adding a `navigateByUrl` method which will extract the query parameters and fragment identifier from the URL string. It will likely be available in the next alpha release.

That said, in your example you should continue using `NavigationParams` instead of `toUrl()`. Using `toUrl()` means you'd be doing double the work to serialize your query, only to have the router immediately de-serialize it.
