### ISSUE TITLE
router-outlet inside a ngIf

### ISSUE THREAD

**Issue by xavierhainaux** [dart-lang/angular#1321]
Dart VM version: 2.0.0-dev.55.0 (Mon May 14 09:23:07 2018 +0200) on "windows_x64"
angular: 5.0.0-alpha+11
angular_router: 2.0.0-alpha+11

I have 2 nested `router-outlet`. The second one is inside a `ngIf`. This second router-outlet seems to not be correctly created when the condition is toggled to true.

Full reproduction:

```dart
import 'dart:async';

import 'package:angular/angular.dart';
import 'package:angular_router/angular_router.dart';

import 'main.template.dart' as self;

@GenerateInjector(const [
  routerProvidersHash,
])
final InjectorFactory injector = self.injector$Injector;

main() {
  runApp(
    self.BodyComponentNgFactory,
    createInjector: injector,
  );
}

@Component(
    selector: 'body',
    template: '<router-outlet [routes]="routes"></router-outlet>',
    directives: const [RouterOutlet])
class BodyComponent {
  final List<RouteDefinition> routes = [
    new RouteDefinition(
        routePath: new RoutePath(path: ''),
        component: self.AppComponentNgFactory),
  ];
}

@Component(selector: 'my-app', template: '''
<button (click)="isInitialized = true">Initialize</button>
<div *ngIf="isInitialized">
  <h2>App initialized</h2>
  <router-outlet [routes]="routes"></router-outlet>
</div>
''', directives: [routerDirectives, coreDirectives])
class AppComponent {
  // If `isInitialized is initially `true`, then the router-outlet works!
  bool isInitialized = false;

  final List<RouteDefinition> routes = [
    new RouteDefinition(
        routePath: new RoutePath(path: '', useAsDefault: true),
        component: self.FirstPageComponentNgFactory),
  ];
}

@Component(selector: 'first-page', template: 'FirstPage')
class FirstPageComponent {}
```

When I click on the "Initialize" button, the title is displayed correctly but the inner page is not.
If we hardcode the variable `isInitialized` to true, then it works.

I try to convert an AngularDart3 app to AngularDart5 and this behavior took me hours to reproduce.

Is this the expected behaviour? How can I workarround this?

**Comment by leonsenft** [comment]
Unfortunately this is expected behavior, and there isn't much we can do to fix this without refactoring the router.

Version 2 of the router uses dynamic router configuration. Upon navigation the router has to build the component tree in order to resolve a URL to a hierarchy of matching routes. If you happen to have an `NgIf` that hides a router outlet, it can't complete this resolution.

Now your case is a little special. Even though the router can't resolve the nested route, the initial route is a sufficient match for '/', which is why it renders at all instead of failing to navigate. It might be possible to have the nested outlet render the matching route when created by the `NgIf`, but this would have very inconsistent results. If you tried navigating to a nested route with a non-empty path, it wouldn't work. Are you wanting this to work for nested routes with non-empty paths too, or just the empty path like your example?

You could try moving the `NgIf` into the nested route? Although this may make achieving the layout you desire impossible.

There is another rather convoluted and messy workaround that I wouldn't recommend unless you absolutely need it. Create a second router-outlet that is shown when the other is hidden, and add a single route to an empty component that matches anything (or better yet, matches any of the real nested routes -- you might need multiple routes for this). This will allow navigation to succeed. When you want to display the nested route, update the condition bound to `NgIF`, then invoke `router.navigate()` on the current path, with `NavigationParams(reload: true, replace: true)`. This will trigger the router to navigate which will instruct the router outlets to render their components. Note it's important your routed components also `extend CanReuse` to prevent them being recreated (and resetting their state -- which may hide the `NgIf` again).

**Comment by xavierhainaux** [comment]
Hello Leon,
Thank you for the explanation. 

I will try to find a workaround with `router.navigate(reload: true/replace: true)`.

> there isn't much we can do to fix this without refactoring the router

Can you tell us if there is some planned work for improving this version of the router? Is this router the one used inside Google for AdWord?

**Comment by leonsenft** [comment]
> Can you tell us if there is some planned work for improving this version of the router?

We're always working to improve the current version, but a change of this magnitude would be a whole new version, which we have no short term plans to do. We're currently observing use across many apps and collecting valuable feedback such as yours. Please continue to file issues if you have trouble with this version. 

> Is this router the one used inside Google for AdWord?

I can't comment on internal projects.

**Comment by NilsAtGoogle** [comment]
This thread is old, but I wanted to suggest another workaround:  Use a guarding component that puts *ngIf around it's content children.  This should allow the router-outlet's constructor to execute (which sets up the relationship to its parent)

Something like
`
<some-guard [showIf]="someExpression">
  <router-outlet [routes]="myRoutes"></router-outlet>
</some-guard>
`
