### ISSUE TITLE
modify the route entry file name, resulting in an incomplete path

### ISSUE THREAD

**Issue by no-if** [dart-lang/angular#1403]
https://github.com/angular-examples/toh-6

modify the file name web/index.html to web/main.html

http://localhost:8080/main.html to http://localhost:8080/#dashboard
Refresh
wrong address http://localhost:8080/#dashboard Not Found
correct address http://localhost:8080/main.html#dashboard

click Heroes to http://localhost:8080/#heroes
Refresh
wrong address http://localhost:8080/#heroes Not Found
correct address http://localhost:8080/main.html#heroes

**Comment by chalin** [comment]
Yes, that is expected. If you rename the `index.html` file then that will impact the URL at which you access your app. That has nothing to do with Angular, it has to do with how `index.html` files are treated. Why are you renaming `index.html`? (I can't think of any use cases where you would need to do that.)

**Comment by xavierhainaux** [comment]
I was personally also surprise that "index.html" is treated differently than others html:
https://github.com/dart-lang/angular/blob/master/angular_router/lib/src/location/location.dart#L193

I spend hours tracking a bug because of this.

I have a web folder with plenty of entry points named other than index.html. And I actually advice to not use "index.html" because of this difference.

**Comment by xavierhainaux** [comment]
Yes, you are right that some web servers serve the `index.html` when requesting a directory. But not the other way: it doesn't redirect you to the directory you when you are requesting `index.html`.

The bug hit me when I was when trying to port my app to the new router. Lot of pieces were moving and I was switching between HashStrategy and PathStrategy to understand the new behavior. In the end the bug was on my end, but it was painful to understand that my 2 tests pages were behaving differently because of their name.

**Comment by chalin** [comment]
> But not the other way: it doesn't redirect you to the directory you when you are requesting `index.html`.

You may have a point there, but I vaguely recall this behavior from the AngularTS router too (but I could be mistaken).

@leonsenft - any comment about https://github.com/dart-lang/angular/blob/master/angular_router/lib/src/location/location.dart#L193 and why it is there?

**Comment by leonsenft** [comment]
@chalin 

Unfortunately no idea, we inherited it that way.
