### ISSUE TITLE
Improve and facilitate error reporting for annotations

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#1494]
When validating constant values obtained from analysis of annotations, it's difficult to provide any relevant context in our warning and error messages.

For example, today if you have an invalid template, you'll get a messages like the following:

```
line 1, column 6 of AppComponent: ParseErrorLevel.FATAL: Can't bind to 'foo'
since it isn't a known native property or known directive. Please fix typo or
add to directives list.

<div [foo]="bar"></div>
     ^^^^^^^^^^^
```

We even have source information from the analyzer for *some* Dart source:

```
line 9, column 15 of package:.../app_component.dart: @HostListener
must be on a non-static member
  static void foo(int yes) {}
              ^^^
```

Where we don't have access to such source information is when dealing with constant values obtained from annotations.

For example, the following use of `Typed` is invalid.

```dart
@Component(
  ...
  directiveTypes: [
    Typed<List>.of([12]),
  ],
)
class AppComponent {}
```

This currently produces the following error, sans context.

```
Expected a type argument of "Typed" to be of one of the following
types:
  * "Symbol"
  * "Type"
  * "Typed"
Go an expression of the type "int".
```

Ideally we could augment this message with the following contextual source information.

```
line X, column Y of package:Z: Expected a type argument... (continued)
    Typed<List>.of([12]),
                    ^^
```

Unfortunately, the finest granularity of source information we get from Dart analyzer APIs is the annotation AST itself.

We could retain a reference to the source annotation, walk its AST as we compute the constant value, and use offsets to compute source information, but this solution is highly error prone.

Ideally the analyzer APIs themselves could offer better support for this task, and if not, perhaps such functionality could be encapsulated in a standalone package or incorporated into source_gen.

**Comment by leonsenft** [comment]
/cc @MichaelRFairhurst 

@matanlurey mentioned this has come up before and that your team wanted to be included in the discussion.

**Comment by MichaelRFairhurst** [comment]
Not to be too bold in my comment here, but there will probably never be a perfect API for this in the analyzer, because there are too many pathological cases.

Think of all of the places a constant value could come from:

- a toplevel
- a different file
- a part file
- an initializer in the class
- an initializer in a parent class
- the result of any const calculation

and the value could come from somewhere used multiple places:

```
const foo = 12;

@Annotation(
  intField: foo,
  stringField: foo,
) ...
```

in this case, you _don't_ want to report that "foo should be String," because it also has to be an int.

Other pathological things:

- const subclass of List
- const subclass of Typed
- const subclass of Component/Directive

If you treat it as an inspection of the final value, you can be hit by any and all of these pathological cases. The calculation is really complex, so reversing it is even more complex.

You want to treat it as a calculation, I think. Now, in theory, you still have to handle all of these cases, but in reality, I think it will be easier to degrade when they come up.

One means of treating it as a calculation is to walk the AST and do stricter checks than the dart analyzer would do.

Another is to extend Dart/change your API so that you don't need to do stricter checks than the dart analyzer.

Another is probably to add asserts inside your const initializers and/or constructors, in which case the calculation can fail at analysis & compile time.

A last approach is we can essentially try to make the const subset of Dart have reversible calculations at run-(analysis)-time. This is the equivalent of doing like:

```
if (foo.bar.baz.qux is! FooBar) {
  throw SourceCodeInitializationLocationError.of(foo.bar.baz.qux);
}
```

and getting an error of where `foo.bar.baz.qux` was initialized, instead of an error at the site of the throw. And getting the initializer expression instead of the resulting value. There are lots of good reasons no languages work this way, and the analyzer is a dart interpreter here so its affected by many of the same concerns, for instance performance.

But also just that the error could have been in a lot of spots -- `qux` could be wrong, or `baz` could be wrong, or `bar` could be wrong, or `foo` could be.

**Comment by leonsenft** [comment]
We discussed offline and concluded this solution can't be well generalized, nor will a analyzer-driven solution be available anytime in the near future.

We'll revisit this discussion in the future if significant analyzer or framework changes can be made (in a future major release) to accommodate or eliminate this issue.
