### ISSUE TITLE
[routerLink]="RoutePaths.hero.toUrl(parameters: {'idParam': '$id'})" generates  'IdentityMap<String, dynamic>' should be 'IdentityMap<String, String>' 

### ISSUE THREAD

**Issue by fmatuszewski** [dart-lang/angular#1601]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* [Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "windows_x64" ] Dart SDK Version (`dart --version`)
* [^5.0.0 ] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
* [Windows ] Whether you are using Windows, macOS, or Linux (if applicable)
* [Chrome ] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
* [ ] Any other packages or constraints we should know about

Missing some or all of the above might make the issue take longer or be impossible to act on.

Step To Recreate
git clone https://webdev.dartlang.org/angular/tutorial/toh-pt5 

Replace dashboard_component.html with content

```
<!--Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "windows_x64"-->
<!---->
<h3>Top Heroes</h3>
<div class="grid grid-pad">
  <a *ngFor="let hero of heroes" class="col-1-4"
     [routerLink]="heroUrl(hero.id)">
    <div class="module hero">
      <h4>{{hero.name}}</h4>
    </div>
  </a>
  <!--This block of code generates an error Type 'IdentityMap<String, dynamic>' should be 'IdentityMap<String, String>'-->
  <a *ngFor="let hero of heroes" class="col-1-4"
     [routerLink]="RoutePaths.hero.toUrl(parameters: {'idParam': '$id'})">
    <div class="module hero">
      <h4>{{hero.name}}</h4>
    </div>
  </a>
</div>
<hero-search></hero-search>

```
Description:
Using functions to route with parameters works fine but when I try to add this to template
[routerLink]="RoutePaths.hero.toUrl(parameters: {'idParam': '$id'})"
I gen an error 
EXCEPTION: Type 'IdentityMap<String, dynamic>' should be 'IdentityMap<String, String>' to implement expected type 'Map<String, String>'.

Probably it is not blocking one

----

For questions consider using Stack Overflow instead:
https://stackoverflow.com/questions/tagged/angular-dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/angular

-----

**Comment by leonsenft** [comment]
@fmatuszewski Thanks for filing, but this is working as intended due to a limitation in our ability to perform inference on nested expressions bound in templates. Collection literals are rewritten to a proxy that returns a new instance each time the bound contents change. When one is the root expression of a binding in a template, we can do partial inference to determine the expected type to proxy, but when they're nested (such as your case it's the parameter to a chained method call) we can't properly infer the type.

Please see https://github.com/dart-lang/angular/issues/844#issuecomment-369436762 for more information.

The workaround is simply to move the expression back into your component's source code. If you need a local template value, you can pass it into a function which constructs and returns the desired value.
