### ISSUE TITLE
Components should support a root-element that is an SVG

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1671]
```dart
@Component(
  selector: 'svg:[example]'
  directives: [],
  template: '<svg:path [attr.example]="name"></svg:path>',
  changeDetection: ChangeDetectionStrategy.OnPush,
)
class SvgHostComponent {
  @Input()
  String name;
}
```

**Comment by matanlurey** [comment]
It looks like we call `createElementNS` with the wrong arguments:

```dart
_el_0 = doc.createElementNS('http://www.w3.org/2000/svg', 'path');
```

... instead of:

```
_el_0 = doc.createElementNS('http://www.w3.org/2000/svg', 'svg', 'path');
```

**Comment by matanlurey** [comment]
On second look, this looks valid:
https://stackoverflow.com/questions/22806022/how-to-use-svg-namespace-in-xhtml-documents

**Comment by ranquild** [comment]
Is this supported? Tried `svg:[example]` selector and it resuled in `createElement` call, not `createElementNS`. @matanlurey

**Comment by jamesopstad** [comment]
As far as I can tell you can't currently split an SVG into smaller components because the elements are inserted with the wrong namespace. Is this correct and if so will this be supported in the future?  All other major frameworks/libraries support this as far as I know (except the ones that explicitly use web components).
