### ISSUE TITLE
Structural directive will be not injected to its `childrens`

### ISSUE THREAD

**Issue by valakis** [dart-lang/angular#1767]
Attribute Directives will be provided to the Component to which they are bound, but Structural Directives will not. This is a bit confusing, especially because Structural Directives are 'functioning' like a parent container.

**Comment by leonsenft** [comment]
Could you please provide an example demonstrating the issue?

**Comment by valakis** [comment]
The first one will fine, and the second one will throw `Invalid argument(s): No provider found for MyStructuralDirective`
```
@Component(
    selector: 'app-cmp',
    template: '<item myStructuralDirective></item>',
    directives: [ItemComponent, MyStructuralDirective])
class AppComponent {}

@Component(selector: 'item', template: 'Text')
class ItemComponent {
  final MyStructuralDirective myStructuralDirective;

  ItemComponent(this.myStructuralDirective);
}

@Directive(selector: '[myStructuralDirective]')
class MyStructuralDirective {}
```

```
@Component(
    selector: 'app-cmp',
    template: '<item *myStructuralDirective></item>',
    directives: [ItemComponent, MyStructuralDirective])
class AppComponent implements AfterViewInit {
  @ViewChild(MyStructuralDirective)
  MyStructuralDirective myStructuralDirective;

  @override
  void ngAfterViewInit() => myStructuralDirective.activate();
}

@Component(selector: 'item', template: 'Text')
class ItemComponent {
  final MyStructuralDirective myStructuralDirective;

  ItemComponent(this.myStructuralDirective);
}

@Directive(selector: '[myStructuralDirective]')
class MyStructuralDirective {
  final TemplateRef _templateRef;
  final ViewContainerRef _viewContainer;

  MyStructuralDirective(this._viewContainer, this._templateRef);

  void activate() => _viewContainer.createEmbeddedView(_templateRef);
}
```

**Comment by leonsenft** [comment]
Thanks for the example, that's because the directive's _visibility_ is restricted to its local view. When you use it as a structural directive, its contents are in another (embedded) view.

https://github.com/dart-lang/angular/blob/bb5642c9a6e71ee38852e0ae9bae02cb286c26ac/angular/lib/src/core/metadata.dart#L128-L133

All directives used to be available for injection to all children (across view boundaries) by default, but there's actually a code size cost for supporting this feature. So now you must opt-in to this behavior by setting the visibility on the directive you wish to inject across views:

```dart
@Directive(
  selector: '[myStructuralDirective]',
  visibility: Visibility.all,
)
class MyStructuralDirective { ... }
```

For more details see https://github.com/dart-lang/angular/blob/master/angular/lib/src/core/metadata/visibility.dart.
