### ISSUE TITLE
ChangeDetectorRef.detectChanges() necessary after window.resize event update

### ISSUE THREAD

**Issue by morrica** [dart-lang/angular#1839]
Change detection does not seem to be run after a component property is updated via a window.resize event handler. It is necessary to call ChangeDetectorRef.detectChanges() to force change detection. Using OnPush with ChangeDetectorRef.markForCheck() does not work.

**Dart SDK Version (`dart --version`)**
Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "linux_x64"
**AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)**
Angular Version 5.3.1
**Whether you are using Windows, macOS, or Linux (if applicable)**
Linux
**Whether you are using Chrome, Safari, Firefox, Edge (if applicable)**
Chrome
**Any other packages or constraints we should know about**
None

We are using this to detect window width changes and make decisions about what components to display accordingly. Example code illustrating the issue below:
**Deprecated But Works:**
```dart
import 'dart:html';

import 'package:angular/angular.dart';
import 'package:angular_components/utils/browser/window/module.dart';

@Component(
  selector: 'test',
  template: "<h1>Current Width = {{width}}</h1>",
//  changeDetection: ChangeDetectionStrategy.OnPush,
)
class TestComponent implements OnInit {

  final ChangeDetectorRef _changeDetectorRef;

  int width = getWindow().innerWidth;

  TestComponent(this._changeDetectorRef);

  @override
  void ngOnInit() {
    getWindow().addEventListener("resize", updateWidth);
  }

  updateWidth(Event event) {
    width = getWindow().innerWidth;
    print("New Width = $width");
//    _changeDetectorRef.markForCheck();
    _changeDetectorRef.detectChanges();
  }
}
```

**Recommended But Does Not Work:**
```dart
import 'dart:html';

import 'package:angular/angular.dart';
import 'package:angular_components/utils/browser/window/module.dart';

@Component(
  selector: 'test',
  template: "<h1>Current Width = {{width}}</h1>",
  changeDetection: ChangeDetectionStrategy.OnPush,
)
class TestComponent implements OnInit {

  final ChangeDetectorRef _changeDetectorRef;

  int width = getWindow().innerWidth;

  TestComponent(this._changeDetectorRef);

  @override
  void ngOnInit() {
    getWindow().addEventListener("resize", updateWidth);
  }

  updateWidth(Event event) {
    width = getWindow().innerWidth;
    print("New Width = $width");
    _changeDetectorRef.markForCheck();
//    _changeDetectorRef.detectChanges();
  }
}
```
Somewhat new to AngularDart so I could be totally overlooking another reason the width change is not being shown in the template, but I can't find anything that looks wrong.

Is this a bug in change detection or could it be an overlooked reason not to deprecate ChangeDetectorRef.detectChanges()?

**Comment by jarsj** [comment]
I use dom_ruler from angular_components. That seems to work with markForCheck.

**Comment by leonsenft** [comment]
Sorry for the delayed response. This is working as intended. Browser events are run outside the Angular zone, so by default Angular doesn't trigger a change detection cycle (which is why it only works for you when you call `detectChanges()` manually).

The correct way of scheduling another change detection cycle is to re-enter the Angular zone when handling a browser event:

```dart
class TestComponent implements OnInit, OnDestroy {
  TestComponent(this._changeDetectorRef, this._ngZone);

  final ChangeDetectorRef _changeDetectorRef;
  final NgZone _ngZone;

  StreamSubscription<void> _windowResizeSubscription;

  @override
  void ngOnInit() {
    _windowResizeSubscription = window.onResize.listen((event) {
      _ngZone.runGuarded(handleResize);
    });
  }

  @override
  void ngOnDestroy() {
    _windowResizeSubscription.cancel();
  }

  void handleResize() {
    ...
    _changeDetectorRef.markForCheck(); // If using OnPush.
  }
}
```

*On a side note, make sure you remove the event listener to prevent a leak! This is more easily done using the `onResize` stream from dart:html.*

This is how event bindings in templates are implemented, they get wrapped in the following method which performs the steps shown above:

https://github.com/dart-lang/angular/blob/44d8ee96f03e54fadb1fbdf0e021570f8d88f6da/angular/lib/src/core/linker/views/render_view.dart#L134-L139

You can read more about this here: https://github.com/dart-lang/angular/blob/master/doc/advanced/async.md
