### ISSUE TITLE
Transforming streams in templates

### ISSUE THREAD

**Issue by zacharydenton** [dart-lang/angular#207]
It would be great to have a way to transform a stream before listening to it in templates. Something along the lines of:

`<search-input (changed.debounce)="fetchSearchResults()"></search-input>`

Before Angular creates the stream listener, it would transform the stream like `searchInput.changed.transform(debounce())`, where `debounce()` is a component method that returns a stream transformer. The stream transformation should only happen once before the listener is created so that the stream transformer can maintain any internal state it needs.

An alternative syntax that would allow for chaining transformations would be a pipe-based syntax, either `<search-input (changed | debounce)="fetchSearchResults()">` or `<search-input (changed)="debounce | fetchSearchResults()">`.

**Comment by matanlurey** [comment]
Just an update: We're unlikely to get to this until after 4.0.

**Comment by matanlurey** [comment]
Would love to get @leonsenft to weigh in here.

**Comment by leonsenft** [comment]
Overall I'm in favor of this idea, but I have a few concerns.

1. This pushes logic into views which is generally discouraged. Unfortunately there's really no way around this unless we were to expose the stream which would introduce other, arguably bigger issues.
2. This won't work for native DOM events. Currently there's no distinction to the user whether they're registering a stream subscription or a DOM event handler. However, it would be easy enough to prevent this at compile time and issue a descriptive message.

**Comment by TedSander** [comment]
I'm wondering why it wouldn't work for DOM events. Is angular not using the stream coming from dart:html for the original event? Or is there an optimization there?

Also this seems like it could be a more generic syntax of something that is already supported. For example angular already has modifiers for DOM events. (keydown.enter) (keydown.shift.x) I would imagine these are much more performant because it doesn't have the StreamTransformer overhead which wouldn't surprise me if it had a higher overhead than I would expect.

I would think sharing transformer logic across components similar to forms validation, or pipes would be better as I could see these being pretty generic.

I'd be worried about a couple of things:
1. The possible performance overhead of streams transformers.
2. Teams wanting/trying to change configuration to a transformer and getting unexpected results

**Comment by leonsenft** [comment]
@TedSander No, for native DOM events Angular uses [EventTarget.addEventListener()](https://api.dartlang.org/dev/2.0.0-dev.19.0/dart-html/EventTarget/addEventListener.html). I'm guessing this is both more optimal, and as I recently found out, there aren't stream properties for all events.

The key event modifiers are supported by the [KeyEventsPlugin](https://github.com/dart-lang/angular/blob/master/angular/lib/src/platform/dom/events/key_events.dart#L98). The entire [EventManagerPlugin](https://github.com/dart-lang/angular/blob/master/angular/lib/src/platform/dom/events/event_manager.dart#L9) system may go away as it does slow down event handling. That concern aside, it's still not a suitable approach for this issue because the API is callback based, so we still wouldn't have access to the underlying stream.

To address your concerns:

1. We'll only implement this in a case that would have cost for those opting to use it. And ideally it shouldn't have any more overhead than adding the stream transformer to a raw stream yourself.

For example, adding a debounce transformer to an existing stream should change code like this:

```html
<div myDirective (stream)="onData($event)">
```
```dart
ComponentRef<MyComponent> build() {
  _MyDirective = new MyDirective();
  final subscription = _MyDirective.stream.listen(eventHandler1(ctx.onData));
}
```

To this:

```html
<div myDirective (stream.debounce)="onData($event)">
```
```dart
ComponentRef<MyComponent> build() {
  _MyDirective = new MyDirective();
  final subscription = _MyDirective.stream
      .transform(ctx.debounce())
      .listen(eventHandler1(ctx.onData));
}
```

2. Could you elaborate on this concern please? I don't quite understand.

**Comment by TedSander** [comment]
Thanks for the explanation.

For 2. I would imagine a user might want to be able to pass in the amount of time to debounce which is in the stream_transform common util we have. I'd hope we would be very clear about what happens and the contract of trying to change a parameter such as that.

A corollary to this is validators and pipes that have configuration abilities. Today we probably aren't clear enough what changing these configurations at runtime after initialization actually does. For example changing an input in a validator does not revalidate that control. It will only affect the next change to the control.

**Comment by leonsenft** [comment]
Oh I see your concern. That's a great point, since stream subscription happens at build time, there are a few limitations.

1. The stream transformer would have to be non-null at build time.
2. The output binding can't have a new stream transformer applied to it after build time.

**Comment by TedSander** [comment]
So if that is the case I would want the API to enable that to be as clear as possible. For example perhaps using injection, or const in the annotation but not allowing arbitrary properties. I'm not exactly sure what it would look like, but I'd prefer to make it clear what the limitations are ideally in using a language angular feature that matched those limitations.

**Comment by leonsenft** [comment]
Matan and I were discussing a pipe-like solution with fewer limitations, but then the concern shifts to performance.

@zacharydenton would you care to weigh in on this issue? Do you see value in having the stream transformer adapt to changes?

**Comment by zacharydenton** [comment]
It should be fine for the stream transformer definition to be static as long as the instance variables of the component/directive are in scope (enabling dynamic behavior).

**Comment by matanlurey** [comment]
> as long as as the instance variables of the component/directive are in scope

@zacharydenton Want to give an example here?

**Comment by zacharydenton** [comment]
```dart
class MyComponent {
  StreamTransformer filter;
  bool isPaused = false;

  MyComponent() {
    filter = new StreamTransformer.fromHandlers(handleData: (event, sink) {
      if (!isPaused) sink.add(event);
    });
  }

  void togglePaused() => isPaused = !isPaused;
}
```

**Comment by matanlurey** [comment]
Ah great, that makes total sense.

@leonsenft thoughts?

**Comment by matanlurey** [comment]
Cool. We could even assert in dev mode that this doesn't change identity.

**Comment by leonsenft** [comment]
That would work is the transformer is a field, but the original proposal suggested a method which returned one. In the latter case, it would be reasonable for the method to return a new instance on each invocation, so we couldn't really check it that case.

I guess it depends if there's a strong argument in favor of one approach or the other, or if we support both since we can analyze if it's a function or a property?

**Comment by matanlurey** [comment]
I'm closing due to it not being on any immediate plans. We can re-visit in the future.
