### ISSUE TITLE
AngularDart should ship a CLI for common actions

### ISSUE THREAD

**Issue by filiph** [dart-lang/angular#380]
Each full AngularDart component needs a folder with three files (.dart, .css, .html) in the recommended setup (yes, you can inline style and template to the Dart file, but that's almost never done in real projects).

AngularTS has [`angular_cli`](https://github.com/angular/angular-cli) which helps people build new components. Polymer has [Polymer CLI](https://www.polymer-project.org/2.0/docs/tools/polymer-cli) with a similar feature set.

In Dart, we could do things like:

```
$ pub run angular create component MyCustomComponent
```
 or

```
$ pub run angular:new_element MyCustomComponent
```

The support for CLI is already baked into pub. And it also means that you can just run `pub run global activate angular` once and then the above examples get much shorter (`angular create component`).

**Comment by matanlurey** [comment]
One issue is we'd prefer not to add CLI-only dependencies to `angular` (in-fact, going the opposite direction by moving into several sub packages, i.e. `angular_compiler` to encapsulate the AOT-compiler). 

Pub needs to be able to support targets/sub-packages for this to work cleanly; otherwise we might just want to create an `angular_cli` project/package.

**Comment by unicomp21** [comment]
I know it's sad, but codegen can make a huge difference with respect to adoption rates.  Just look at pivotal/spring.  There are far better ways of doing things, yet they dominate due to codegen sugar.  Having a cli for common actions, would go a long ways towards attracting early adopters.  We have a term/concept for "technical debt".  Let's call this "marketing debt".

**Comment by tfzhu** [comment]
Please try this one: https://github.com/google/angular_cli

**Comment by matanlurey** [comment]
Superseded by https://github.com/dart-lang/webdev/issues/1 after discussion.
