### ISSUE TITLE
Redirect doesn't pass parameters to target Route

### ISSUE THREAD

**Issue by fridek** [dart-lang/angular#479]
I'm attempting to redirect users of the old route to a new one.

Old route is
```
  const Route(
      path: '/s/:projectId/',
      component: SettingsComponent,
      name: settingsRoute),
```
New route is

```
  const Route(
      path: '/:projectId/settings',
      component: SettingsComponent,
      name: settingsRoute),
```
Redirect provides no way to pass the ``:projectId`` to the new route

**Comment by leonsenft** [comment]
Sorry, I don't think this is supported. The issue is you'd need to pass the `projectId` in the `redirectTo` list, but it's not possible to access that value from the redirecting link during route configuration.

```dart
@RouteConfig(
  const Route(
    path: ':projectId/settings',
    component: SettingsComponent,
    name: 'Settings',
  ),
  const Redirect(
    path: '/s/:projectId/',
    redirectTo: ['Settings', {'projectId': /* can't access projectId from path */}],
  ),
)
```

There's a new router implementation in development, so I'd rather see it address this issue than add the feature to the old one.

Does it matter to you that the link actually redirects and rewrites the URL, or is having both route to the same component good enough? If the latter, you can simply have both route definitions in your configuration linking to the same component.

**Comment by fridek** [comment]
This is how I solved it for now, but it's suboptimal. Eventually I'd like to deprecate old routes once I measure the traffic on them is acceptably low. If we keep both it's not going to happen.

It's not a huge problem and if there is a new router coming, I don't mind waiting for it :)

**Comment by zoechi** [comment]
Instead of a `Redirect()` you could use a normal `Route()` with a dummy component, which just takes the parameters and calls `router.navigate(...)`

**Comment by matanlurey** [comment]
We have a new router now, so closing as not planned.
