### ISSUE TITLE
Use synthetic events 

### ISSUE THREAD

**Issue by ranquild** [dart-lang/angular#503]
Currently angular listens to DOM events directly. If you add 1 event listener to 1000 items list you will have 1000 event listeners in DOM. Large amount of DOM event listeners have great impact on application performance.

This is common issue and modern DOM frameworks (React, Inferno, ...) use synthetic event system so there is only one event listener per event type on document. Can you add such feature to angular as well?

**Comment by matanlurey** [comment]
I believe @leonsenft tried this with mixed results. Maybe he can expand.

**Comment by leonsenft** [comment]
As mentioned in https://github.com/dart-lang/angular/issues/441, our benchmarks indicated this wasn't much of a performance improvement, and was actually a regression for simple cases which is why we didn't land it. However, I don't think any of the benchmarks demonstrated the best case improvements.

@ranquild have you found this to have a significant performance in your applications? Perhaps it would be worth evaluating again and comparing the tradeoffs.

We could even explore allowing users or the compiler to choose between a native and synthetic event subscription if the tradeoffs are too extreme.

**Comment by ranquild** [comment]
@leonsenft Sorry for delay, I have performance issues with attaching event listeners to each cell in large table. We have 500 rows x 10 columns table with few mouse events attached. But this is extreme scenario; also, we would have even worse performance with attaching events to document.body. So we just did manual event delegating at table level. It would be *nice* to have some framework support for doing this, still, it is not common case and I think this issue can be closed.
