### ISSUE TITLE
const Provider(<class>) provides null

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#579]
Using `const Provider(<class>)` without the `useClass` parameter provides `null` when used in `@Component` or `@Directive` annotations.

```dart
final myProviders = const [
  const Provider(MyProvider),
];

@Component(
  ...
  providers: myProviders,
)
class MyComponent {
  MyComponent(MyProvider myProvider) {
    // `myProvider` is null.
  }
}
```

Note that this isn't an issue if `myProviders` is provided in `bootstrap`.

Current workarounds are to use `const Provider(MyProvider, useClass: MyProvider)` or simply `MyProvider` directly.

**Comment by leonsenft** [comment]
Considering if you use `const Provider(MyProvider)` in `bootstrap` it will actually provide `MyProvider`, I think the expected behavior is that it should provide an instance of `MyProvider` when used in class annotations as well.

**Comment by zoechi** [comment]
If someone wants the short form just `MyProvider` is IMHO the better one, therefore `const Provider(MyProvider)` looks like a bug to me, where just assuming `MyProvider` hides that possible bug. Giving me a hint that this is probably not what I intended would be helpful and an indication that otherwise just `MyProvider` is enough would make the developers life easier for the future, because she learned how to safe keystrokes.

**Comment by leonsenft** [comment]
That's a good argument actually. Perhaps issue a warning rather than error once it's fixed? Making `const Provider(MyProvider)` an error could be a needless breaking change.

@matanlurey Thoughts?

**Comment by matanlurey** [comment]
The form of `MyProvider` will eventually not be supported.

I plan on fixing `const Provider(MyProvider)`, but it's not a high priority today.

**Comment by zoechi** [comment]
Then it makes sense of course. Forgot about that. I think you (@matanlurey) mentioned that a while ago already.

**Comment by leonsenft** [comment]
Here's the relevant issue describing the change #407.

**Comment by matanlurey** [comment]
Sorry this took so long. Have a fix now :)
