### ISSUE TITLE
Consider renaming `<ng-content>` to `<@content>`?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#648]
Rationale:

* `<ng-content>` is not a `@Directive` or `@Component`.
* Unlike most elements in a template, you don't put it in `directives: [ ... ]`
* It is entirely a compile-time operation.

Low priority, but came up in internal code labs with @TedSander

**Comment by adaojunior** [comment]
My impression is that when I'm using `<ng-content>` I don't actually realize that it is neither a `@Directive` or `@Component`. But what matters (IMHO) is that this is very natural/familiar because I've been using a similar tag since  angular js and even with polymer 1x which was the first library to use the `<content>` tag for this purpose.

Also, I believe `<ng-content>` looks better than `@content`, see example:

```
<@content></@content>

vs 

<ng-content></ng-content>
```

**Comment by zoechi** [comment]
I think it's named this way because it emulates the native `<content>` element behavior.
So it's just an element. I find addind `@` to it's name weird.
To be consistent this would rquire to rename `<template>` to `<@template>` (I'd prefer `<ng-template>`)

There were also plans to replace `<content>` with `<slot>` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot
which could make `<ng-content>` obsolete eventually.

I see such a change ony causing a lot of confusion.

**Comment by matanlurey** [comment]
Not planned.
