### ISSUE TITLE
Only fully matching router links are considered active

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#737]
Consider an application with a nested set of router links. The first is a set of top-level navigation links that persist across all views, below which may appear another set of contextual links. For example, the following page corresponds to the route `/products/apparel`.

> Home | **Products** | About | Help
> **Apparel** - Electronics - Groceries

The `RouterLinkActive` directive is used to toggle a class name on an element when it's route is considered active. Unfortunately this only works if the full route matches the link, and doesn't take into account default or sub-routes.

There are three issues here.
1. If the "Products" header links to `/products`, it will be active, but the default sub-route itself won't be if it's path is non-empty.
2. If the "Products" header links to `/products`, it won't be active when any of the sub-route links are clicked.
3. If the "Products" header links explicitly to a sub-route `/producs/apparel`, then both will be active as desired, but then "Products" won't be active when another sub-route is clicked.

Instead, `RouterLinkActive` should consider any link with a matching prefix as active.

**Comment by chalin** [comment]
Is this planned for v5? /cc @kwalrath

**Comment by leonsenft** [comment]
I felt low priority as no one but me had reported it, but I can try and have it in for 5.

**Comment by matanlurey** [comment]
@leonsenft Still planned for v5 final?

**Comment by leonsenft** [comment]
Haven't prioritized this yet. I'll try to get this done for 5.0.0, but it's not a blocker.

**Comment by matanlurey** [comment]
I'm removing from the v5 list, since we could easily do this after.

**Comment by matanlurey** [comment]
We don't plan this change.

**Comment by shashikantdurge** [comment]
Any updates on this? Please...

**Comment by kingkazuma** [comment]
in angular_router 2.x, AuxRouter is removed
So, how to implement sub-routes?

**Comment by leonsenft** [comment]
@kingkazuma The same way you implement top-level routes. Just add a `<router-outlet>` and set its `[routes]`. The router will discover any nested `<router-outlet>`s during navigation and use them to resolve sub-routes.

**Comment by saibotma** [comment]
It this still in "not planned" state? I have run into a problem where I could really need this feature.

**Comment by leonsenft** [comment]
@saibotma We're not planning to work on this, but contributions are welcome.

**Comment by jarsj** [comment]
Incase someone wants a workaround, routerLinkActive is a very simple directive. Just put this file anywhere and instead of [routerLinkActive] you can use [routerLinkActivePrefix] to get this behavior. 

`// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:async';
import 'dart:html';

import 'package:collection/collection.dart';
import 'package:angular/angular.dart';
import 'package:angular/src/runtime.dart';

import 'package:angular_router/angular_router.dart';

/// Adds a CSS class to the bound element when the link's route becomes active.
///
/// ```html
/// <a routerLink="/user/bob" routerLinkActive="active-link">Bob</a>
/// ```
///
/// May also be used on an element containing a [RouterLink].
/// ```html
/// <div routerLinkActive="active-link">
///   <a routerLink="/user/bob">Bob</a>
/// </div>
/// ```
@Directive(
  selector: '[routerLinkActivePrefix]',
)
class RouterLinkActivePrefix implements AfterViewInit, OnDestroy {
  final Element _element;
  final Router _router;

  StreamSubscription<RouterState> _routeChanged;
  List<String> _classes;

  @ContentChildren(RouterLink)
  List<RouterLink> links;

  RouterLinkActivePrefix(this._element, this._router);

  @override
  void ngOnDestroy() => _routeChanged?.cancel();

  @override
  void ngAfterViewInit() {
    _routeChanged = _router.stream.listen(_update);
    _update(_router.current);
  }

  @Input()
  set routerLinkActivePrefix(Object classes) {
    if (classes is String) {
      _classes = [classes];
    } else if (classes is List<String>) {
      _classes = classes;
    } else if (isDevMode) {
      throw ArgumentError(
        'Expected a string or list of strings. Got $classes.',
      );
    }
  }

  void _update(RouterState routerState) {
    var isActive = false;
    if (routerState != null) {
      for (var link in links) {
        final url = link.url;
        if (!routerState.path.startsWith(url.path)) continue;
        // if (url.path != routerState.path) continue;
        // Only compare query parameters if specified in the [routerLink].
        if (url.queryParameters.isNotEmpty &&
            !const MapEquality<String, String>()
                .equals(url.queryParameters, routerState.queryParameters)) {
          continue;
        }
        // Only compare fragment identifier if specified in the [routerLink].
        if (url.fragment.isNotEmpty && url.fragment != routerState.fragment) {
          continue;
        }
        // The link matches the current router state and should be activated.
        isActive = true;
        break;
      }
    }
    _element.classes.toggleAll(_classes, isActive);
  }
}
`
