### ISSUE TITLE
removeEventListener not working

### ISSUE THREAD

**Issue by Cododoc** [dart-lang/angular#751]
Hello.
When I add document event listener in my component, then it will not remove.

For example. I have a method open, that call **addEventListener:**
```
  void open() {
    _isOpen = true;
    document.addEventListener('keyup', closeOnEsc, true);
  }
```

Another method, call **removeEventListener:**
```
  void close() {
    _isOpen = false;
    document.removeEventListener('keyup', closeOnEsc, true);
    _changeDetectorRef.detectChanges();
    _onCloseCtrl.add(null);
  }
```

**closeOnEsc**
```
void closeOnEsc(Event event) {
    if (isOpen && event is KeyboardEvent) {
      if (event.keyCode == 27) {
        close();
      }
    }
  }
```

I try to call method call on destroy, on button click and on key press. Listener not removed.

**Comment by jonahwilliams** [comment]
Try using an anonymous function stored in a class member field instead.  This ensures that the function is always identical and can be removed correctly.  (I believe the reason you are running into this problem is that closeOnEsc is actually a tear off, and so the object passed to remove event listener is not the same one used to register).

```dart
final closeOnEsc = (Event event) { ... }

void open() {
  document.addEventListener('keyup', closeOnEsc, true);
}

void close() {
  document.addEventListener('keyup', closeOnEsc, true);
}
```

Alternatively, you could use the Stream based event listener API for [document](https://api.dartlang.org/stable/1.24.3/dart-html/Document/onKeyUp.html).  This automatically handles adding and removing event listeners and is cleaned up by unsubscribing.

```dart
StreamSubscription _onKeyUp;

void ngOnInit() {
  _onKeyUp = document.onKeyUp.listen(closeOnEsc);
}

void ngOnDestroy() {
  _onKeyUp?.cancel();
}
```

**Comment by leonsenft** [comment]
Thanks @jonahwilliams.

**Comment by Cododoc** [comment]
Thank you for your help @jonahwilliams
