### ISSUE TITLE
router-outlet inside of a conditional isn't found if you call a child route

### ISSUE THREAD

**Issue by akaufmann** [dart-lang/angular#805]
If you have a `router-outlet` within an element with  e.g.`*ngIf` and a child route is used (with `useAsDefault`) the `router-outlet` will not be found (no error/warn/info).

```dart
import 'planning_routes.dart' as planning_routes;
import 'home_component.template.dart' as home_component;
import 'details_component.template.dart' as details_component;

import 'planning_service.dart';

@Component(
    selector: 'my-app',
    directives: const [routerDirectives],
    providers: const [PlanningService],
    template: '''
      <div *ngIf="planning != null">
        <router-outlet [routes]="routes"></router-outlet>
      </div>
    ''')
class PlanningComponent implements OnActivate {
  final List<RouteDefinition> routes = [
    new RouteDefinition(
      routePath: planning_routes.homeRoute,  // useAsDefault: true
      component: home_component.PlanningHomeComponentNgFactory,
    ),
    new RouteDefinition(
      routePath: planning_routes.detailRoute,
      component: details_component.PlanningDetailsComponentNgFactory,
    ),
  ];
  Planning planning;
  PlanningService _planningService;

  PlanningComponent(this._planningService);

  @override
  onActivate(_, RouterState routerState) async {
    planning = await _planningService.getPlanning(routerState.parameters['planType']);
  }
}
```

Output:
```html
  <div class="_ngcontent-oaq-2">
    <router-outlet class="_ngcontent-oaq-2"></router-outlet>
  </div>
```

If you call the nested route directly (through `routerLink`), you will receive an error message:

```js
dart_sdk.js:62993 EXCEPTION: NullError: Cannot read property 'activate' of null
STACKTRACE: 
package:angular_router/src/router/router_impl.ddc.js 307:31             _activateRouterState
package:$sdk/dev_compiler/amd/dart:async 146:50                         onValue
package:stack_trace                                                     arg
package:$sdk/dev_compiler/amd/dart:async/zone.dart 
...
```

```shell
angular version: "2.0.0-alpha+4"
```

**Comment by leonsenft** [comment]
It's necessary for the router to know if a route is valid _before_ it navigates and renders the new view. The router has no way of knowing your `PlanningComponent` has any nested routes, since the router outlet  embedded in an `NgIf` doesn't exist when first created. This makes it impossible to validate whether a requested path matches a valid route.

This is an unfortunate limitation of the router's design. Because routes are registered as an input to each router outlet, they aren't known ahead of time. When you instruct the router to navigate, it incrementally matches the requested path to the available routes in the root router outlet, and recurses on a match. If a router outlet doesn't exist immediately upon initialization, the router can't discover it and any of its routes.

**Comment by akaufmann** [comment]
Thank you @leonsenft for your explanation. What confused me a bit was that the main router outlet (in AppComponent) works embedded in an `ngIf`. Hmm, too bad it doesn't work for child routes as well. I guess I'll have to put in a few more `ngIf`'s or restructure my HTML.

**Comment by leonsenft** [comment]
The reason it will work for the root outlet is because it registers itself with the router upon initialization, which will occur when the view embedded in `NgIf` is created:

https://github.com/dart-lang/angular/blob/5e8d5b2644bd2315b1a8bfab32a7627ff3f0529b/angular_router/lib/src/directives/router_outlet_directive.dart#L87-L92

This in turn triggers the initial navigation:

https://github.com/dart-lang/angular/blob/5e8d5b2644bd2315b1a8bfab32a7627ff3f0529b/angular_router/lib/src/router/router_impl.dart#L61-L76
