### ISSUE TITLE
DDC failures with pkg/build missing source maps

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#871]
![screen shot 2018-02-12 at 1 47 40 pm](https://user-images.githubusercontent.com/168174/36121528-507d395e-0ffb-11e8-9dbb-06ed405462fc.png)

/cc @grouma @jakemac53 @natebosch 

I'm not sure if this is pkg/test or pkg/build. Please help me triage this.

**Comment by grouma** [comment]
My guess is that this is a builder or more likely a DDC issue.

package:test gets the stack trace produced from DDC here:
https://github.com/dart-lang/test/blob/master/lib/src/runner/remote_listener.dart#L63

The test package does some mapping in the Dart2JS case but otherwise uses the stack trace as is, filtering out lines where appropriate:
https://github.com/dart-lang/test/blob/master/lib/src/frontend/test_chain.dart#L40

@vsmenon made a fix a while back for Google3 to correctly produce a stack trace using source maps. I'm told that the change was tested only internally:
https://github.com/dart-lang/sdk/commit/f95daf6168dcf3a4c9f3af5d99d7baa09dee5e32#diff-ffba419d3c8dce67d5927059ce87f5ad

I have a couple questions:
1) Is the stack trace produced correctly when running locally, or is this strictly a Travis issue?
2) Are the source maps loaded in the browser? (not sure how to check this on Travis)

**Comment by matanlurey** [comment]
> Is the stack trace produced correctly when running locally, or is this strictly a Travis issue?

Not sure, just noticed it on Travis today.

**Comment by matanlurey** [comment]
@grouma Yes, it occurs locally too:

```
 ~/git/angular/angular_test  ⑂ master ⇡31    pub run test -p chrome --precompiled build
00:06 +0 -1: test/frontend/bed_static_test.dart: should create a component with a ComponentFactory [E]
  Bad state: Could not find a factory for BrowserExceptionHandler.
  ../packages/$sdk/dev_compiler/amd/dart_sdk.js 4903:29                  throw
  ../packages/angular/src/di/reflector.ddc.js 62:17                      getFactory
  ../packages/angular/src/di/injector/empty.ddc.js 344:28                _assertProviders
  ../packages/angular/src/di/injector/empty.ddc.js 45:36                 resolveAndCreate
  ../packages/angular_test/src/bootstrap.ddc.js 39:67                    createTestInjector
  ../packages/angular_test/src/bootstrap.ddc.js 59:51                    bootstrapForTest
  ../packages/angular_test/src/frontend/bed.ddc.js 275:33                FutureOfNgTestFixtureOfT.sync.dart.fn
  ../packages/$sdk/dev_compiler/amd/dart_sdk.js 26406:24                 sync
  ../packages/angular_test/src/frontend/bed.ddc.js 273:43                [_createDynamic]
  ../packages/angular_test/src/frontend/bed.ddc.js 262:36                create
```

**Comment by matanlurey** [comment]
Might be related, but some classes of errors get no stack trace at all:

```
00:02 +0 -1: should create a component with a ComponentFactory [E]
  NullError: Cannot read property 'addStyles' of null
```

**Comment by matanlurey** [comment]
To reproduce, make some silly error in `_tests/test/**_test.dart`, and then:

```bash
$ pub run build_runner build
$ pub run test -p chrome --precompiled build
```

**Comment by jakemac53** [comment]
You can repro this with e2e_example in the build repo as well, just add a test failure into test/hello_world_test.dart and load http://localhost:8081/hello_world_test.debug.html in your browser (or run `pub run build_runner test -- -p chrome`.

**Comment by vsmenon** [comment]
Note, this is the utility that DDC uses (if available) to map JS stack traces back to Dart ones:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/web/stack_trace_mapper.dart

This code is actually compiled via dart2js as a separate 'binary' on the page - see its `main` - it registers with DDC.  We include this on the html page - is this also there in the test case?

**Comment by jakemac53** [comment]
@vsmenon it is there in the test case yes, but its difficult to debug since its compiled with dart2js haha

**Comment by grouma** [comment]
I confirmed that the source maps are present and work (at least for debugging). I also confirmed that the stack trace provided to package:test from DDC is not correctly mapped. I'm fairly positive the issue resides with stack_trace_mapper.dart inside DDC. @jakemac53 said the build structure is slightly different in the external world which likely is the root cause. I think @vsmenon will need to jump in as he knows that class the best.

**Comment by matanlurey** [comment]
As discussed offline, I believe either @jakemac53 and/or @grouma will need to own this?

**Comment by grouma** [comment]
Discussed with @jakemac53. He'll lead the investigation and I can help out when needed.

**Comment by jakemac53** [comment]
All the code to fix this has been submitted. With the next build_runner release it will be fixed except for `dart:` libraries which will be fixed in the next dev release of the sdk. We can probably do a build_runner release today.

**Comment by jakemac53** [comment]
Ok, build_runner 0.7.11 is now published. Things should be a bit better (at least you will see dart files) but they won't be fully correct until the sdk release. The frames won't be collapsed, and the dart sdk paths will be weird.

**Comment by matanlurey** [comment]
Re-opened as I still don't see this fixed at HEAD.

Here is the latest failure encountered by a user in the wild:
![image](https://user-images.githubusercontent.com/168174/37616829-59540e34-2b6e-11e8-8adf-99c160c3cb24.png)

You'll notice:
* Source maps are not applied.
* The actual error is some giant text blob, and doesn't show up as a browser stack trace (not clickable)

**Comment by natebosch** [comment]
It is interesting that `require.js` is showing up there. I can't remember if that's something we've seen in other cases. @vsmenon - is this a different type of failure than before? Something during the loading rather than execution?

https://github.com/dart-lang/build/issues/1151 is still open which also might be what we're seeing.

**Comment by matanlurey** [comment]
At HEAD I see the following:

```
EXCEPTION: Type 'String' is not a subtype of type 'num'
STACKTRACE: 
dart:sdk_internal 4656:17                                      dsend
main.dart 14:13                                                new
main.template.dart 56:32                                       build
package:angular/src/core/linker/app_view.dart 240:12           createHostView
package:angular/src/core/linker/component_factory.dart 111:15  create
package:angular/src/core/application_ref.dart 68:37            src__runtime__optimizations.unsafeCast.run.dart.fn
package:angular/src/core/change_detection/host.dart 252:18     runInZone.dart.fn
package:angular/src/core/zone/ng_zone.dart 177:16              parent.run.dart.fn
dart:sdk_internal 28604:14                                     run
package:angular/src/core/zone/ng_zone.dart 174:18              [_run]
dart:sdk_internal 28805:14                                     run
package:angular/src/core/zone/ng_zone.dart 312:22              run
package:angular/src/core/application_ref.dart 137:49           runInZone
package:angular/src/core/change_detection/host.dart 250:5      run
package:angular/src/core/application_ref.dart 67:23            bootstrap
package:angular/src/bootstrap/run.dart 188:16                  runApp
main.dart 5:16                                                 main
main.dart.bootstrap.js 185:12                                  <fn>
dart:sdk_internal 1717:29                                      onScriptLoad
```

... so marking this done! Thanks @natebosch @grouma @jakemac53 et al!
