### ISSUE TITLE
Support sub-classing {Opaque|Multi}Token

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#899]
Forked from https://github.com/dart-lang/angular/issues/288:

> One more potential requirement is that internal users are sometimes scared of using a single application global (i.e. `#...`) as the identifying token. We should explore allowing users to sub-class ~~`Inject`~~`OpaqueToken`:
> 
> ```dart
> class XsrfToken extends OpaqueToken<String> {
>   const XsrfToken();
> }
> ```

**Comment by matanlurey** [comment]
Initial implementation is going to have a _lot_ of restrictions, mostly to be able to keep the list of supported list classes to an absolute minimum. It's cheap to expand more functionality in the future versus constantly fix bugs if we miss edge cases.

Known restrictions:
* Classes must not be `abstract`
* Classes must not be private (prefixed with `_`)
* Classes must be `const` (i.e. have a `const` constructor)
* Classes must have a default (unnamed) constructor, only.
* Classes must not have type parameters.
* Classes must not have parameters to the constructor.
* Classes must directly extend `OpaqueToken` or `MultiToken`.
* Classes must not implement or mixin any other interfaces or classes.

**Comment by parren-google** [comment]
After the great Dart `const` keyword cleanup, tokens have become a bit error-prone. Copy/pasting a token provider from a const context to a non-const context leads to bugs that can be very hard to diagnose. The same happens if one changes a provider list from const to non-const when adding non-const providers to it (in a test typically). For example:
```
const providers = [FactoryProvider.forToken(FooToken(), ...)];
```
vs
```
var providers = [FactoryProvider.forToken(FooToken(), ...), someNonConstProviders];
```

The reason is that in the non-const context, the token is implicitly created as `new FooToken()` rather than `const FooToken()`. And so the const token and the new token aren't equal (which the docs for OpaqueToken do point out, but that doesn't help with an accidental change). Before the `const` keyword cleanup, tokens all had their individual `const FooToken()` const-ness. So one was unlikely to make inadvertent changes to it. But now they inherit it from their outer context, which is error-prone.

One way to fix this would be with something like this:
```
class ClassToken<T> extends OpaqueToken<T> {
  const ClassToken();  
  bool operator ==(o) => o.runtimeType == this.runtimeType;
  int get hashCode => this.runtimeType.hashCode;
}

class FooToken extends ClassToken<bool> {
  const FooToken();
}
```

However, that currently runs afoul of this error: "A sub-type of OpaqueToken must directly extend OpaqueToken or MultiToken, and cannot extend another class that in turn extends OpaqueToken or MultiToken."

Also, it actually seems to me that the simpler fix would be to avoid subclassing `OpaqueToken`, and instead go back to:
```
const fooToken = OpaqueToken<bool>('foo');
const barToken = OpaqueToken<bool>('bar');
```

What would be reasons that we should, in fact, prefer subclassing to the above?
