### ISSUE TITLE
Add testing infrastructure for running the compiler

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#903]
We're going to be spending more time making sure we cover success and failure cases in the compiler, and throw actionable error messages (instead of stack traces). That means we need a super easy way to run tests asserting this.

I'm imagining this in `_tests`, for now.

```dart
/// Returns a future that completes, asserting potential end states.
///
/// File [input] is treated as the primary input source. Additional
/// sources can be added via the [include] and [inputSource] properties:
/// ```
/// compilesExpect('...',
///   inputSource: 'pkg|lib/input.dart', 
///   include: {
///     'pkg|lib/input.html': '...',
///     'pkg|lib/other.dart': '...',
///   }
/// )
/// ```
///
/// Note that `package:angular/angular.dart` is always included.
Future<Null> compilesExpecting(
  String input, {
  dynamic /*Matcher|Iterable<Matcher>*/ errors,
  dynamic /*Matcher|Iterable<Matcher>*/ warnings,
  dynamic /*Matcher|Iterable<Matcher>*/ notices,
  dynamic /*Matcher|Map<String, Matcher>*/ output,
});

/// Returns a future that completes, asserting no errors or warnings occur.
///
/// An alias [compilesExpecting] with `errors` and `warnings` asserting empty.
Future<Null> compilesNormally(String input);
```

Thoughts @leonsenft @alorenzen @natebosch?

**Comment by leonsenft** [comment]
Yes, I'd love to see infrastructure for testing compilation. Ever since the move from the run-time compiler to ahead of time, we actually lost some coverage for error cases since the behavior was untestable (since it didn't compile!), the template parser tests being an exception.

Are we okay with `compilesNormally()` ignoring `notices`? Shouldn't we fully test what messages we show the user?

**Comment by matanlurey** [comment]
Notices don't show up by default in either Bazel or BuildRunner.
