### ISSUE TITLE
The router is not destroying the components before creating and initiating the new route components

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/angular#910]
Hi,

The new router has a different cycle of events from the previous router.
This is the new cycle when a route changes:

Creating AComponent...
AComponent ngOnInit...
Creating BComponent...
BComponent ngOnInit...
AComponent ngOnDestroy...

So, before the A route's components are destroyed, the B components are already created and initiated.
The previous router would destroy the components before the new route components are initiated

sample attached
[provider.zip](https://github.com/dart-lang/angular/files/1744034/provider.zip)

**Comment by leonsenft** [comment]
This is an unfortunate consequence of two router design choices.

**Dynamic configuration**
Routes are declared as inputs to each `<router-outlet>`, meaning their presence is only known if that `<router-outlet>` exists. While this introduces more flexibility in configuring routes, it also means the router has to actually create all of the constituent routes to see if they exist while resolving a URL during navigation.

**Activation Guards**
`CanActivate` is an interface a routed component may implement to guard activation. While supporting this on the component gives us the benefit of using injected dependencies (you could for example inject an authentication service), it also means the component has to be created and checked for guards before it can be activated.

Since we don't want to destroy the current route if the new route doesn't exist or can't be activated, it's necessary that the new route's components be created before the current are destroyed.

**Comment by jodinathan** [comment]
I have a message service that any component can inject and use. It is as simple as : ```messageService.show("Hi!")```

I have two messages viewer:

*DialogViewerComponent*
It uses material_components and shows a dialog with the message.

*ToastViewerComponent*
It uses a custom component that temporarily shows the message at the corner of the page.

They should not co-exist.
Once one is deployed to a template, it "attach" itself to the messageService and listen to a stream of messages (that is fed by the ```messageService.show```).

As we are creating every component and it's children for each route, angular ends up creating and initiating both of viewers, thus, both attach themselves to the service, creating unexpected results and exceptions.

Maybe we could use an interface like CanActivate where it adds a property like: ```List<RouteDefinition> ngRoutes``` so we don't have to create the whole tree of components just to read the routes?

**Comment by leonsenft** [comment]
Have you looked at the `OnActivate` interface? This will be invoked after the route has been resolved, and the previous routes destroyed. You can implement this interface in both components and begin listening to the stream on activation. Likewise, you can cancel the subscription using `OnDeactivate`.

```dart
@Component(...)
class ToastViewerComponent implements OnActivate, OnDeactivate {
  final MessageService _messageService;

  StreamSubscription<String> _subscription;

  ToastViewerComponennt(this._messasgeService);

  @overrride
  void onActivate(RouterState previous, RouterState current) {
    _subscription = _messageService.stream.listen(_showToast);
  }

  @override
  void onDeactivate(RouterState current, RouterState next) {
    _subscription.cancel();
  }

  void _showToast(String message) { ... }
}
```

**Comment by jodinathan** [comment]
so children components of the route component also have a OnActivate event?
Didn't know that. I thought it was only a route-component like cycle

**Comment by leonsenft** [comment]
Oh no you're right. They'll only be invoked on routed components. Sorry, this is a _very_ unfortunate shortcoming of the router's design.

I guess as a workaround you could wrap the components which use this service in an `ngIf` which you display on activation and hide on deactivation?

**Comment by jodinathan** [comment]
I will create a workaround, but will not be as efficient as a destroy and init of the component. I mean, the viewers should not know the existence of the routes, nor the service etc.
imho, we should not depend on parsing the component's template to know the routes that the component exposes.

**Comment by leonsenft** [comment]
>I mean, the viewers should not know the existence of the routes, nor the service etc.

Yeah I totally agree with you.

>we should not depend on parsing the component's template to know the routes that the component exposes.

Parsing is done at compile time. What the router does depend on is _binding_ at run-time (since the routes are defined as an input to the outlet) to discover the router configuration. This allows for dynamic route configuration.

Personally I don't think it's worth the drawbacks and would prefer a static system.

**Comment by Pianisimo** [comment]
Hi, have you found a good solution? I am having problems with the component not being destroyed if route guard fails to activate them.

**Comment by krel024** [comment]
I am having the same issue and as far as I see no body found a good solution for this.

**Comment by snapfast** [comment]
Use `routerLink` and `<router-outlet></router-outlet>` instead of going with below technique (I think it is older technique) 
```javascript
gotoSignup() {
    this.router.navigate(['/signup']);  // define your component where you want to go
}
```

You can do something like this.
```html

<button mat-flat-button color="primary" routerLink="/login">Login</button>
<button mat-flat-button color="primary" routerLink="/signup">Signup</button>

<router-outlet></router-outlet>
```

Your Components will show in place of `<router-outlet></router-outlet>` and they will destroy previous component. [[Source](https://angular.io/guide/router-tutorial)]

Thoughts:
I believe this way of routing is done because of the 'nature' of the Single Page Applications.
