### ISSUE TITLE
Dart2: (keypress) expects (Event e) not (KeyEvent e)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#915]
This fails at the DDC with errors enabled:

https://github.com/dart-lang/angular/blob/f55fea736cb25040be640e75541acfbcd34e0329/_tests/test/core/change_detection/detect_host_changes_test.dart#L67

... I'm not sure why, yet. The temporary fix is to type this `Event`.

**Comment by leonsenft** [comment]
@matanlurey What's the actual error?

**Comment by matanlurey** [comment]
"Expected KeyEvent e got Event e"

**Comment by leonsenft** [comment]
So the issue arises from the following generated line:

```dart
_el_0.addEventListener('keypress', eventHandler1(_SomeDirective_0_5.handleKeyPress));
```

`Element.addEventListener()` expects a listener of type `void Function(Event)`, which prevents a user from writing a handler with a specialized event type. Normally you'd write one that accepts `Event`, then cast (if you're certain of the type) or promote the event. For example, if you're listening to the `click` event, you know the event type will be `ClickEvent`.

I tried to do this work for the user if they specified a type with the following code:

https://github.com/dart-lang/angular/blob/f55fea736cb25040be640e75541acfbcd34e0329/angular/lib/src/core/linker/app_view.dart#L629-L634

My thinking was when this function is invoked directly as a parameter of `EventTarget.addEventListener()`, the parameter type requires `E` to be `Event`, thus `F` is restricted to a type that's assignable to `Event`. We then cast this `Event` to `F` in the _returned_ closure which itself has type `void Function(Event)`.

Is there a mistake in my reasoning? Is inference not intended to be capable of handling this? I looked at the output of dart2js and found this.

```javascript
this[_el_0][$addEventListener](
  'keypress',
  this.eventHandler1(
    html.Event,
    html.Event,
    EventTovoid()._check(dart.dload(this[_SomeDirective_0_5], 'handleKeyPress')),
  ),
);
```

By the looks of the parameters (which I assume are the generic type arguments), inference has typed `eventHandler1<E, F extends E>` as `eventHandler<Event, Event>`. This is why we see the error `cast fail from (KeyEvent) => void to (Event) => void`, since the parameter isn't expecting a `void Function(KeyEvent)` as it should, but rather a `void Function(Event)`.

So is this a dart2js bug, or am I misunderstanding the type system?

**Comment by vsmenon** [comment]
@leonsenft The inference will only work if we know the static type of `_SomeDirective_0_5.handleKeyPress`.  The `dload` in the generated code means that it doesn't.   What's the static type of `_SomeDirective_0_5`?

**Comment by leonsenft** [comment]
Of course! The field has type `dynamic`. I'm wondering why this is the case, since a directive's type should be well known (you have to provide it in the metadata directly). I'll double check if all directives have dynamic types, or if this is just a special case since the directive is being provided by the component hosting it.

Thanks!

**Comment by matanlurey** [comment]
I am going to assume this is a bug (?) in the compiler, and assign to you for now.
