### ISSUE TITLE
Support a curated list of directives: const [ ... ]

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#936]
This is a meta-tracking issue.

I know `angular_analyzer_plugin` (/cc @MichaelRFairhurst) supports a bit of this.

* [ ] Emit warnings (later errors?) for unused directives and components:

```dart
@Component(
  selector: 'not-used',
  template: '',
)
class NotUsed {}

@Component(
  selector: 'example',
  directives: const [
    NotUsed,
  ],
  template: '',
)
class Example {}
```

* [ ] Emit warnings (later errors?) for tag names that aren't matched.

This is a _little_ harder. We do this "for free" for structural directives today, but we don't for normal components or directives. There are a couple options here:

* Add a tag whitelist, and allow the user to supplement it in compiler options.
* Support an alternative way to render an angular component. My pick:

```html
<div>
  <HelloWorld></HelloWorld>
</div>
```

(Capitalized tags are assumed to be components, and don't require the `selector`).

* ?????

**Comment by MichaelRFairhurst** [comment]
the plugin doesn't actually expose this yet!

Its on my wishlist, but it complicates the dependency order (analyze dart,
in order to be able to analyze html, in order to finish analyzing dart...).

Its not that complicated but its been enough to keep it off my next-in-line
queue...though this would usefully also allow me to validate
@ViewChildren().

**Comment by matanlurey** [comment]
We are tracking this elsewhere.
