### ISSUE TITLE
Validate that code snippets in docs are at least "analyzer clean"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#996]
I believe (?) @chalin and others had a tool for this at one point.

Basically I'd have love to catch that:

```md
const ClassProvider(Foo, ConcreteFoo);
```

... was an incorrect example (missing the `useClass: ` named parameter).

Might not be worth doing, though.

**Comment by chalin** [comment]
If this is related to #992, I was going to suggest that we integrate that page into [site-webdev](https://github.com/dart-lang/site-webdev) since we have there the necessary infrastructure allowing code excerpts to be analyzed and/or tested.

Actually, as @kwalrath mentioned already, it might be a good idea to have an **Effective Angular** section under site-webdev, similar to the **[Effective Dart][]** section under dartlang.org.

[Effective Dart]: https://www.dartlang.org/guides/language/effective-dart

FYI, regarding tooling, the Flutter site has some tooling to extract code excerpts and then analyze them. Under site-webdev, we use the usual tools to analyzer and test code. Instead we have a code excerpt extractor that scans the code, picks out fragments, and embeds the fragments into the docs. The approaches are complementary.

**Comment by matanlurey** [comment]
As mentioned elsewhere, I'd really like this to be in our own repository. This stuff changes often, and the cognitive load of needing to land the CL separate to updating the best practices doesn't seem worth it.

**Comment by alorenzen** [comment]
Also, if it is in our own repository, we can reference it easier internally as well.
